project:
  type: book
  output-dir: docs
  

book:
  title: "0023_learning_diary"
  author: "Qiyue Chen"
  date: "1/18/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Week01.qmd
    - Week02.qmd
    - Week03.qmd
    - Week04.qmd
    - Week06.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

