# Personal Introduction {.unnumbered}

Hi, this is Qiyue Chen, a student of Msc Urban Spatial Science. I come from Hainan Province, China, which is very beautiful and chill island ! I finished my undergraduate degrees at Xi'an Jiaotong-Liverpool University and studied in Urban Planning and Design. In my past academic and internship experiences, I have developed a strong interest in urban sustainable development, particularly in low-carbon urban development strategies including land use, urban form and transport systems. 

During my undergraduate studies, I mainly learned the use of Geographic Information System (GIS) and gained some knowledge of Geographical Science. However, when exploring urban issues , I discovered that remote sensing data has broader application prospects. 

In the course projects related to urban analysis, I used relatively inefficient methods to analyse urban sprawl, relying on manual classification for data processing and visuaalisation. This approach may have affected data accuracy and limited precision. However, through the study of remote sensing in this course, I will be able to combine machine learning methods to solve the limitations I encountered in my undergraduate studies, I will combine them with machine learning methods to address the limitations I encountered in my undergraduate studies. This will also open up more possibilities for my future learning and career development.

Studying urban planning has exposed me to the diverse urban histories, sparking a keen interest in tourism and city walk. From delving into masterplans on a theoretical level to experiencing cities firsthand and feeling their unique social and cultural identities, I have developed a profound fascination with the discipline. I look forward to further exploring the diversity and development potential of cities through quantitative and spatial analysis in the future.

